# Generated by Django 4.2.18 on 2025-01-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kinogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KinoogoModel',
            new_name='KinoogoParser',
        ),
    ]
